### PR TITLE
Submitting homework 3

### PR DESCRIPTION
**Pull request by DaltonLaCoste**

### CODE REVIEW

**Comment by connolly** [comment]
Very good! 14pts

1. I dont see the derivation for this question
2. Excellent! 10pts
 - great use of legend to label plots and for calculating age not lookback time
 - age and distance calculations look good
3. Very nice. 4pts

**Comment by DaltonLaCoste** [comment]
Is the derivation for question 1 not displaying properly? I just ran my notebook again and everything looks fine.
[image1.jpeg]
I may have made some mistake in markdown, but I definitely did the derivation. Is there something I need to fix?

- Dalton

On Nov 1, 2016, at 22:28, Andrew Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


Very good! 14pts

  1.  I dont see the derivation for this question
  2.  Excellent! 10pts
     *   great use of legend to label plots and for calculating age not lookback time
     *   age and distance calculations look good
  3.  Very nice. 4pts

-

**Comment by connolly** [comment]
Yes it was a problem with the rendering. I reran it and it looks good. I updated the score

**Comment by DaltonLaCoste** [comment]
Thanks! I'll be a bit more careful with what I submit next time.

- Dalton

On Nov 2, 2016, at 13:13, Andrew Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes it was a problem with the rendering. I reran it and it looks good. I updated the score

-

**Pull request merged**
